
version: "3.7"

services:
  rocksdb:
    image: rocksdb/0.0.1:latest
    environment:
      - ROCKSDB_PATH=/etc/rocksdb
    volumes:
      - type: bind
        source: ./db
        target: /etc/rocksdb
    ports:
      - "8089:8080"